services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=exercisetracker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=exercisetracker
      - DB_SSLMODE=disable
      # Or provide a single DATABASE_URL instead of the above
      # - DATABASE_URL=postgres://user:password@postgres:5432/exercisetracker?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
